import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Container from "@/components/Container";

const inter = Poppins({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "TMDB App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={inter.className}>
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
